---
 - hosts: all

   tasks:
   - name: Disable Root Login
     lineinfile:
           dest: /etc/ssh/sshd_config
           regexp: '^PermitRootLogin'
           line: "PermitRootLogin no"
           state: present
           backup: yes
     become: yes
     notify:
       - restart ssh

   handlers:
   - name: restart ssh
     systemctl:
       name: sshd
       state: restarted
